## Practice 1: Creating Arrays

**Q1.** Create a 1D array of numbers from 10 to 50 using NumPy.

In [33]:
import numpy as np
np.array(np.arange(10,51,1))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Q2.** Create a 2D array of shape (3, 4) filled with ones.

In [34]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Q3.** Convert the following list to a NumPy array and print its shape:
```python
data = [[3, 5, 1], [6, 7, 9], [8, 4, 2]]
```

In [35]:
#Note: This code worked without importing NumPy particularly for the current cell. As I understood, the reason is related to the RAM that stores the "np" as the name of NumPy library in the current kernel, while all the cells in the same file here are in the same kernel.
data=[[3,5,1],[6,7,9],[8,4,2]]
data_arr=np.array(data)
print(np.shape(data_arr))

(3, 3)


## Practice 2: Shape & Dimensions

**Q4.** Given an array:
```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
```
- What is the shape and dimension of the array?

In [36]:
arr=np.array([[1,2],[3,4],[5,6]])
print(f"shape of arr :{np.shape(arr)}")
print(f"dimension on arr: {np.ndim(arr)}")

shape of arr :(3, 2)
dimension on arr: 2


## Practice 3: Reshaping and Transposing

**Q5.** Reshape the following array into a shape of (3, 3):
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [37]:
arr=np.array([1,2,3,4,5,6,7,8,9])
reshaped_arr=arr.reshape(3,3)

**Q6.** Transpose the reshaped array and print both.

In [38]:
#Unless the above cells are executed first, this code will give a name error, because (reshaped_arr) is not defined locally in the current cell's scope. 
Transposed=reshaped_arr.T
print(f"reshaped array = {reshaped_arr}")
print(f"Transposed array = {Transposed}")

reshaped array = [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed array = [[1 4 7]
 [2 5 8]
 [3 6 9]]


**Q7.** Write a function to reverse this array.
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [39]:
np.flip(arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## Practice 4: Higher Dimensions

**Q8.** Create a 3D NumPy array with shape (2, 3, 4) containing numbers from 1 to 24.

In [40]:
threeD=np.array(np.arange(1,25,1))
threeD=threeD.reshape(2,3,4)

**Q9.** What is the `.ndim` and `.shape` of the array in Q8?

In [41]:
print(np.ndim(threeD))
print(np.shape(threeD))

3
(2, 3, 4)


## Practice 5: Indexing and Slicing

**Q10.** Create an array from 0 to 9 and extract elements from index 2 to 6.

In [42]:
Array=np.array(np.arange(0,10,1))
print(Array[2:7])

[2 3 4 5 6]


**Q11.** Given a 2D array, retrieve the second row and the third column.

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"second row = {arr[1]}")
print(f"Third col = {arr[:,2]}")

second row = [4 5 6]
Third col = [3 6 9]


## Practice 6: Array Operations

**Q12.** Create two arrays of the same shape and perform element-wise addition, subtraction, and multiplication.

In [58]:
A=np.array([[1,2,1],[0,1,0]]) #shape (2,2)
B=np.array([[0,1,0],[1,2,1]]) #shape (2,2)
#Elements Addition
print(A+B)
#Elements Subtraction
print(A-B)
print(B-A)
#Elemnts Multiplication
print(A*B) 

[[1 3 1]
 [1 3 1]]
[[ 1  1  1]
 [-1 -1 -1]]
[[-1 -1 -1]
 [ 1  1  1]]
[[0 2 0]
 [0 2 0]]


**Q13.** Compute the dot product of:
```python
a = np.array([1, 2])
b = np.array([3, 4])
```

In [ ]:
a=np.array([1,2])# shape(1,2)
b=np.array([3,4])#shape(1,2)
print(np.dot(a,b)) #scalar operation


11


## Practice 7: Mathematical Functions
**Q14.** Use NumPy to compute the square root, exponential, and logarithm of each element in:
```python
arr = np.array([1, 4, 9, 16])
```

In [ ]:
arr=np.array([1,4,9,16])
# First I wrote it like : "for i in range arr:" but it returned an index error, the reason is that i will have the value of the element in this index rather than the index itself, so when it has the value 1 it will access the element 4 in the array, and when it has the value 4 it will search for the element in the fifth index and will not find it.
for i in range(len(arr)):
    print(f"Square root of {arr[i]} = {np.sqrt(arr[i])} || Exponential of {arr[i]} = {np.exp(arr[i])} || Logarithm of {arr[i]} = {np.log10(arr[i])}")

Square root of 1 = 1.0 || Exponential of 1 = 2.718281828459045 || Logarithm of 1 = 0.0
Square root of 4 = 2.0 || Exponential of 4 = 54.598150033144236 || Logarithm of 4 = 0.6020599913279624
Square root of 9 = 3.0 || Exponential of 9 = 8103.083927575384 || Logarithm of 9 = 0.9542425094393249
Square root of 16 = 4.0 || Exponential of 16 = 8886110.520507872 || Logarithm of 16 = 1.2041199826559248


## Practice 8: Boolean Indexing and Filtering
**Q15.** Create an array of 10 random integers between 1 and 100. Filter out the even numbers.

In [ ]:
np.random.seed(42)
randomArr=np.array(np.random.randint(low=1,high=100,size=10))
print(randomArr)
print(randomArr%2==0) #invistigates the even values, returns boolean
evenRandomArr=randomArr[randomArr%2==0]
print(evenRandomArr) #prints the even values in the array

[52 93 15 72 61 21 83 87 75 75]
[ True False False  True False False False False False False]
[52 72]
